-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: e306ff3b7d0d9a6fc7d128ef9ca2e0b6e6e76e8f
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
-   repo: local
    hooks:
    -   id: mix_dogma
        name: Mixing dogma
        entry: mix dogma
        language: system
        files: \.ex$
    -   id: mix_escript
        name: Mixing escript.build
        entry: python -c "import os; os.system('mix escript.build')"
        language: system
        files: xxx.xxx
        always_run: true
